CREATE OR REPLACE PROCEDURE AIRLINE_DB.UTILS.PROC_DWH_TO_DM()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    rows_cnt NUMBER;
BEGIN
    MERGE INTO DM.COUNTRY_STATS AS T
    USING (
        SELECT COUNTRY_CODE, COUNT(*) as NEW_PAX
        FROM DWH.FACT_STREAM
        WHERE METADATA$ACTION = ''INSERT'' AND COUNTRY_CODE IS NOT NULL
        GROUP BY COUNTRY_CODE
    ) AS S
    ON T.COUNTRY_CODE = S.COUNTRY_CODE
    WHEN MATCHED THEN
        UPDATE SET T.TOTAL_PASSENGERS = T.TOTAL_PASSENGERS + S.NEW_PAX, T.LAST_UPDATED = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN
        INSERT (COUNTRY_CODE, TOTAL_PASSENGERS, LAST_UPDATED) VALUES (S.COUNTRY_CODE, S.NEW_PAX, CURRENT_TIMESTAMP());

    rows_cnt := SQLROWCOUNT;

    INSERT INTO UTILS.AUDIT_LOG (PROCESS_NAME, STATUS, ROWS_AFFECTED)
    VALUES (''DWH_TO_DM'', ''SUCCESS'', :rows_cnt);

    RETURN ''Updated DM stats. Rows: '' || :rows_cnt;
END;
';