CREATE OR REPLACE PROCEDURE AIRLINE_DB.UTILS.PROC_RAW_TO_DWH()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    rows_cnt NUMBER DEFAULT 0;
BEGIN
    MERGE INTO DWH.FACT_PASSENGERS AS T
    USING (
        SELECT
            PASSENGER_ID,
            FIRST_NAME || '' '' || LAST_NAME AS FULL_NAME,
            GENDER,
            TRY_TO_NUMBER(AGE) AS AGE,
            NATIONALITY,
            AIRPORT_COUNTRY_CODE AS COUNTRY_CODE,
            TRY_TO_DATE(DEPARTURE_DATE, ''MM/DD/YYYY'') AS DEPARTURE_DATE,
            FLIGHT_STATUS,
            MD5(COALESCE(TO_VARCHAR(PASSENGER_ID),'''') || COALESCE(TO_VARCHAR(DEPARTURE_DATE),'''')) AS HASH_KEY
        FROM RAW.PASSENGERS_STREAM
        WHERE METADATA$ACTION = ''INSERT''
        QUALIFY ROW_NUMBER() OVER (PARTITION BY PASSENGER_ID, DEPARTURE_DATE ORDER BY LOAD_TIMESTAMP DESC) = 1
    ) AS S
    ON T.PASSENGER_ID = S.PASSENGER_ID
    AND T.DEPARTURE_DATE = S.DEPARTURE_DATE

    WHEN MATCHED THEN
        UPDATE SET
            T.FULL_NAME = S.FULL_NAME,
            T.GENDER = S.GENDER,
            T.AGE = S.AGE,
            T.NATIONALITY = S.NATIONALITY,
            T.COUNTRY_CODE = S.COUNTRY_CODE,
            T.FLIGHT_STATUS = S.FLIGHT_STATUS,
            T.HASH_KEY = S.HASH_KEY -- Обновляем хеш, если данные изменились

    WHEN NOT MATCHED THEN
        INSERT (
            PASSENGER_ID, FULL_NAME, GENDER, AGE, NATIONALITY,
            COUNTRY_CODE, DEPARTURE_DATE, FLIGHT_STATUS, HASH_KEY
        )
        VALUES (
            S.PASSENGER_ID, S.FULL_NAME, S.GENDER, S.AGE, S.NATIONALITY,
            S.COUNTRY_CODE, S.DEPARTURE_DATE, S.FLIGHT_STATUS, S.HASH_KEY
        );

    rows_cnt := SQLROWCOUNT;

    INSERT INTO UTILS.AUDIT_LOG (PROCESS_NAME, STATUS, ROWS_AFFECTED)
    VALUES (''RAW_TO_DWH'', ''SUCCESS'', :rows_cnt);

    RETURN ''Merged '' || :rows_cnt || '' rows.'';
END;
';