create or replace TABLE AIRLINE_DB.UTILS.AUDIT_LOG (
	LOG_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	PROCESS_NAME VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	ROWS_AFFECTED NUMBER(38,0),
	LOG_TIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
