create or replace TABLE AIRLINE_DB.DWH.FACT_PASSENGERS (
	ROW_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	PASSENGER_ID VARCHAR(255),
	FULL_NAME VARCHAR(500),
	GENDER VARCHAR(255),
	AGE NUMBER(38,0),
	NATIONALITY VARCHAR(255),
	COUNTRY_CODE VARCHAR(255),
	DEPARTURE_DATE DATE,
	FLIGHT_STATUS VARCHAR(255),
	HASH_KEY VARCHAR(32)
);
