USE DATABASE AIRLINE_DB;

-- DML 1: Statement 5 minutes ago
SELECT count(*) FROM DWH.FACT_PASSENGERS AT(OFFSET => -60*5);

-- DML 2: Data before certain query
SELECT * FROM DWH.FACT_PASSENGERS BEFORE(STATEMENT => '01c0c146-0004-f591-0000-000115b6a025');

-- DDL 1: Recovery the table
DROP TABLE DM.COUNTRY_STATS;
UNDROP TABLE DM.COUNTRY_STATS;

-- DDL 2: Clone creation
CREATE TABLE DWH.FACT_PASSENGERS_BACKUP CLONE DWH.FACT_PASSENGERS;
