USE DATABASE AIRLINE_DB;

-- DML 1: Посмотреть состояние таблицы 5 минут назад
SELECT count(*) FROM DWH.FACT_PASSENGERS AT(OFFSET => -60*5);

-- DML 2: Посмотреть данные до конкретного запроса
SELECT * FROM DWH.FACT_PASSENGERS BEFORE(STATEMENT => '01c0c146-0004-f591-0000-000115b6a025');

-- DDL 1: Восстановление табоицы
DROP TABLE DM.COUNTRY_STATS;
UNDROP TABLE DM.COUNTRY_STATS;

-- DDL 2: Создание мгновенной копии
CREATE TABLE DWH.FACT_PASSENGERS_BACKUP CLONE DWH.FACT_PASSENGERS;